# Generated by Django 5.2.8 on 2025-11-18 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_list',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
