# Generated by Django 5.2.8 on 2025-11-19 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_task_list_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserData',
        ),
    ]
